name: Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip3 install flask-sqlalchemy

      - name: Run database migrations
        run: |
          flask db migrate -m "create_user_table"
          
      - name: Build and deploy
        run: |
          python app.py 
